sed 's/""//g' hmda_lar_ak.csv > ./reformat/hmda_lar_ak.csv
sed 's/""//g' hmda_lar_al.csv > ./reformat/hmda_lar_al.csv
sed 's/""//g' hmda_lar_ar.csv > ./reformat/hmda_lar_ar.csv
sed 's/""//g' hmda_lar_az.csv > ./reformat/hmda_lar_az.csv
sed 's/""//g' hmda_lar_ca.csv > ./reformat/hmda_lar_ca.csv
sed 's/""//g' hmda_lar_ct.csv > ./reformat/hmda_lar_ct.csv
sed 's/""//g' hmda_lar_co.csv > ./reformat/hmda_lar_co.csv
sed 's/""//g' hmda_lar_dc.csv > ./reformat/hmda_lar_dc.csv
sed 's/""//g' hmda_lar_de.csv > ./reformat/hmda_lar_de.csv
sed 's/""//g' hmda_lar_fl.csv > ./reformat/hmda_lar_fl.csv
sed 's/""//g' hmda_lar_ga.csv > ./reformat/hmda_lar_ga.csv
sed 's/""//g' hmda_lar_hi.csv > ./reformat/hmda_lar_hi.csv
sed 's/""//g' hmda_lar_ia.csv > ./reformat/hmda_lar_ia.csv
sed 's/""//g' hmda_lar_id.csv > ./reformat/hmda_lar_id.csv
sed 's/""//g' hmda_lar_il.csv > ./reformat/hmda_lar_il.csv
sed 's/""//g' hmda_lar_in.csv > ./reformat/hmda_lar_in.csv
sed 's/""//g' hmda_lar_ks.csv > ./reformat/hmda_lar_ks.csv
sed 's/""//g' hmda_lar_ky.csv > ./reformat/hmda_lar_ky.csv
sed 's/""//g' hmda_lar_la.csv > ./reformat/hmda_lar_la.csv
sed 's/""//g' hmda_lar_ma.csv > ./reformat/hmda_lar_ma.csv
sed 's/""//g' hmda_lar_md.csv > ./reformat/hmda_lar_md.csv
sed 's/""//g' hmda_lar_me.csv > ./reformat/hmda_lar_me.csv
sed 's/""//g' hmda_lar_mi.csv > ./reformat/hmda_lar_mi.csv
sed 's/""//g' hmda_lar_mn.csv > ./reformat/hmda_lar_mn.csv
sed 's/""//g' hmda_lar_mo.csv > ./reformat/hmda_lar_mo.csv
sed 's/""//g' hmda_lar_ms.csv > ./reformat/hmda_lar_ms.csv
sed 's/""//g' hmda_lar_mt.csv > ./reformat/hmda_lar_mt.csv
sed 's/""//g' hmda_lar_ne.csv > ./reformat/hmda_lar_ne.csv
sed 's/""//g' hmda_lar_nv.csv > ./reformat/hmda_lar_nv.csv
sed 's/""//g' hmda_lar_nh.csv > ./reformat/hmda_lar_nh.csv
sed 's/""//g' hmda_lar_nj.csv > ./reformat/hmda_lar_nj.csv
sed 's/""//g' hmda_lar_nm.csv > ./reformat/hmda_lar_nm.csv
sed 's/""//g' hmda_lar_ny.csv > ./reformat/hmda_lar_ny.csv
sed 's/""//g' hmda_lar_nc.csv > ./reformat/hmda_lar_nc.csv
sed 's/""//g' hmda_lar_nd.csv > ./reformat/hmda_lar_nd.csv
sed 's/""//g' hmda_lar_oh.csv > ./reformat/hmda_lar_oh.csv
sed 's/""//g' hmda_lar_ok.csv > ./reformat/hmda_lar_ok.csv
sed 's/""//g' hmda_lar_or.csv > ./reformat/hmda_lar_or.csv
sed 's/""//g' hmda_lar_pa.csv > ./reformat/hmda_lar_pa.csv
sed 's/""//g' hmda_lar_ri.csv > ./reformat/hmda_lar_ri.csv
sed 's/""//g' hmda_lar_sc.csv > ./reformat/hmda_lar_sc.csv
sed 's/""//g' hmda_lar_sd.csv > ./reformat/hmda_lar_sd.csv
sed 's/""//g' hmda_lar_tn.csv > ./reformat/hmda_lar_tn.csv
sed 's/""//g' hmda_lar_tx.csv > ./reformat/hmda_lar_tx.csv
sed 's/""//g' hmda_lar_ut.csv > ./reformat/hmda_lar_ut.csv
sed 's/""//g' hmda_lar_vt.csv > ./reformat/hmda_lar_vt.csv
sed 's/""//g' hmda_lar_va.csv > ./reformat/hmda_lar_va.csv
sed 's/""//g' hmda_lar_wa.csv > ./reformat/hmda_lar_wa.csv
sed 's/""//g' hmda_lar_wv.csv > ./reformat/hmda_lar_wv.csv
sed 's/""//g' hmda_lar_wi.csv > ./reformat/hmda_lar_wi.csv
sed 's/""//g' hmda_lar_wy.csv > ./reformat/hmda_lar_wy.csv
sed 's/""//g' hmda_lar_pr.csv > ./reformat/hmda_lar_pr.csv
